project_one/app.py
from flask import Flask, render_template            #flask imports
from views import my_view                           #local imports

app = Flask(__name__)
app.register_blueprint(my_view)                     #Sets the blueprint

@app.errorhandler(404)                              #Error handling belongs in the app.py
def page_not_found(e):                              #Function for error handling. e is the variable for the error message. It is built into flask.
    return render_template("404.html", e=e)         #Redirects to our 404.html

if __name__ == "__main__":
    app.run(debug=True, port=8000)                  #debugging is activated only to be used during testing. It is set to be hosted on port 8000

project_one/views.py
from flask import render_template, redirect, Blueprint, url_for

my_view = Blueprint('my_view', __name__)

@my_view.route("/")
def index():
    return render_template("index.html")

@my_view.route("/page1")
def page1():
    return render_template("page1.html")

@my_view.route("/page2")
def page2():
    return render_template("page2.html")
                                                    #Links to 5+ different web pages
@my_view.route("/page3")
def page3():
    return render_template("page3.html")

@my_view.route("/page4")
def page4():
    return render_template("page4.html")

@my_view.route("/admin")
def pageadmin():                                    #Admin redirect to admin page
    return render_template("admin.html")

@my_view.route("/javascript")                        #Redirects for javascript, js and home
@my_view.route("/js")
@my_view.route("/home")
def index_redirect():
    return redirect(url_for("my_view.index"))

project_one/templates/admin.html
{% extends 'base.html' %}

{% block content %}

<body>

<h1>Admin</h1>

</body>

{% endblock %}

project_one/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="{{ url_for('static', filename='app.js')}}"></script>           <!--Javascript linked-->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='main.css')}}">  <!--CSS linked-->
    <title>JavaScript Events</title>
</head>
<body onload="darkCheck()">
<nav>
    <ul>
        <li><a href="{{ url_for('my_view.index') }}">Javascript</a></li>
        <li><a href="{{ url_for('my_view.page1') }}">Page 1</a></li>            <!-- Links to 5 different web pages handled in views.py-->
        <li><a href="{{ url_for('my_view.page2') }}">Page 2</a></li>
        <li><a href="{{ url_for('my_view.page3') }}">Page 3</a></li>            <!--Navbar gives additional support for linking-->
        <li><a href="{{ url_for('my_view.page4') }}">Page 4</a></li>
        <li><a href="{{ url_for('my_view.pageadmin') }}">Admin</a></li>
    </ul>
</nav>


{% block content %}





{% endblock %}
</body>
</html>

project_one/templates/index.html
{% extends 'base.html' %}

{% block content %}

    <div class="flex-container-h">
    <div>
    <h1>JavaScript Events</h1>
    
    <h2>Innovate Coding</h2>
    <p id="intro-text">This is an interactive website for demonstrating a selection of events in JavaScript.</p>

    <div class="flex-container-h">
        <button onclick="darkMode()">Dark Mode</button>
    </div>

    <br>

    <div class="main-box">
    <h3 class="main-title">onclick Events</h3>
    <p class="main-text">This is an event that occurs as a result of the user 'clicking' a specific element.</p>
    <p onclick="changeText(this)" class="example-text">click this text to change it</p>
    <div class="flex-container-h2">
    <button onclick="displayDate(date)" class="example-button">Display Date</button>
    <p class="example-text" id="date"></p>
    </div>
    </div>

    <br>
    <br>

    <div class="main-box">
    <h3 class="main-title">onload Events</h3>
    <p class="main-text">This is an event that occurs as soon as the user has loaded the web page.</p>
    <p class="example-text" id="cookie"></p>
    </div>

    <br>
    <br>

    <div class="main-box">
    <h3 class="main-title">Mouse Events</h3>
    <p class="main-text">This is an event that occurs when the user moves their cursor over a specific element.</p>
    <div class="flex-container-h3">
        <div onmouseover="mOver(this)" onmouseout="mOut(this)" class="colour-box example-text">
        </div>
        <div onmouseover="mOver(this)" onmouseout="mOut(this)" class="colour-box example-text">
        </div>
        <div onmouseover="mOver(this)" onmouseout="mOut(this)" class="colour-box example-text">
        </div>
    </div>
    </div>

    <br>
    <br>

    <div class="main-box">
    <h3 class="main-title">Extra:</h3>
        <p class="main-text">Additional features that can be used in developing a website with JavaScript.</p>
        <h4 class="main-text">Alert</h4>

        <p class="main-text">An alert is used to notify the user via a pop-up window.</p>
        <button onclick="sendAlert()" class="example-button">Display Host Name</button>
        <h4 class="main-text">Toggle</h4>
        <p class="main-text">TBC</p>
    </div>

    <br>
    <br>

    </div>
    </div>
</body>

{% endblock %}

project_one/templates/page1.html
{% extends 'base.html' %}

{% block content %}

<body>

<h1>Future Page 1</h1>

</body>

{% endblock %}

project_one/templates/page2.html
{% extends 'base.html' %}

{% block content %}

<body>

<h1>Future Page 2</h1>

</body>

{% endblock %}

project_one/templates/page3.html
{% extends 'base.html' %}

{% block content %}

<body>

<h1>Future Page 3</h1>

</body>

{% endblock %}

project_one/templates/page4.html
{% extends 'base.html' %}

{% block content %}

<body>

<h1>Future Page 4</h1>

</body>

{% endblock %}