flask_venv/app.py
from flask import Flask
from views import my_view

app = Flask(__name__)
app.register_blueprint(my_view)

if __name__ == "__main__":
    app.run(debug=True, port=8000)

#fgfedog

flask_venv/views.py
from flask import render_template, redirect, Blueprint

my_view = Blueprint('my_view', __name__)

@my_view.route("/")
def home():
    return render_template("home.html")

@my_view.route("theman")
def theman():
    return render_template("theman.html")

@my_view.route("thedog")
def thedog():
    return render_template("thedog.html")

@my_view.route("thevan")
def thevan():
    return render_template("thevan.html")

flask_venv/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css')}}">
    <title></title>
</head>

<body>

    <nav>
        <ul>
            <li><h3><a href="{{ url_for('my_view.home') }}">Home</a></h3></li>
            <li><h3><a href="{{ url_for('my_view.theman') }}">The Man</a></h3></li>
            <li><h3><a href="{{ url_for('my_view.thedog') }}">The Dog</a></h3></li>
            <li><h3><a href="{{ url_for('my_view.thevan') }}">The Van</a></h3></li>
        </ul>
    </nav>

    <header>This is my header.</header>

    {% block content %}

    {% endblock %}

    <footer>This is my footer.</footer>
    <aside>This has extended from base.</aside>

</body>
</html>

flask_venv/templates/home.html
{% extends 'base.html' %}

{% block content %}

<h1>Hello Home</h1>

{% endblock %}

flask_venv/templates/thedog.html
{% extends 'base.html' %}

{% block content %}

<h1>Hello Dog</h1>

{% endblock %}

flask_venv/templates/theman.html
{% extends 'base.html' %}

{% block content %}

<h1>Hello Man</h1>

{% endblock %}

flask_venv/templates/thevan.html
{% extends 'base.html' %}

{% block content %}

<h1>Hello Van</h1>

{% endblock %}